/*
 * zerotiercentralapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package member_pkg

import "zerotiercentralapi_lib/models_pkg"

/*
 * Interface for the MEMBER_IMPL
 */
type MEMBER interface {
    RetrieveAMember (string, string) (*models_pkg.Member, error)

    UpdateOrAddAMember (string, string, *models_pkg.Member) (*models_pkg.Member, error)
}

/*
 * Factory for the MEMBER interaface returning MEMBER_IMPL
 */
func NewMEMBER() MEMBER {
    return &MEMBER_IMPL{}
}