/*
 * zerotiercentralapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package user_pkg

import "zerotiercentralapi_lib/models_pkg"

/*
 * Interface for the USER_IMPL
 */
type USER interface {
    RetrieveAUser (string) (*models_pkg.User, error)

    UpdateAUser (string) (*models_pkg.User, error)

    GetAllViewableUsers () ([]*models_pkg.User, error)
}

/*
 * Factory for the USER interaface returning USER_IMPL
 */
func NewUSER() USER {
    return &USER_IMPL{}
}