/*
 * zerotiercentralapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package network_pkg

import "zerotiercentralapi_lib/models_pkg"

/*
 * Interface for the NETWORK_IMPL
 */
type NETWORK interface {
    RetrieveANetwork (string) (*models_pkg.Network, error)

    UpdateOrCreateANetwork (string, *models_pkg.Network) (*models_pkg.Network, error)

    DeleteANetwork (string) (error)

    GetAllViewableNetworks () ([]*models_pkg.Network, error)
}

/*
 * Factory for the NETWORK interaface returning NETWORK_IMPL
 */
func NewNETWORK() NETWORK {
    return &NETWORK_IMPL{}
}