/*
 * zerotiercentralapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package generalqueries_pkg

import "zerotiercentralapi_lib/models_pkg"

/*
 * Interface for the GENERALQUERIES_IMPL
 */
type GENERALQUERIES interface {
    GetStatusAndConfigurationInformation () (*models_pkg.Status, error)

    GetCurrentlyAuthenticatedUser () (string, error)

    GetGenerateARandomToken () (*models_pkg.RandomToken, error)

    CreateTerminateCurrentSession () (error)
}

/*
 * Factory for the GENERALQUERIES interaface returning GENERALQUERIES_IMPL
 */
func NewGENERALQUERIES() GENERALQUERIES {
    return &GENERALQUERIES_IMPL{}
}